# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
#permalink:           pretty
permalink: /blog/:year/:month/:day/:title/
relative_permalinks: false

# Setup
title:               "Dan's Scrawls"
#tagline:             'foo's website
description:         "Some writing"
url: http://scrawls.danielrayjones.com
baseurl: 
urlimg: https://pbs.twimg.com/profile_images/67492770/200707-Jalaine-453x604-eyes-colored_400x400.jpg
markdown: kramdown
paginate: 5
paginate_path: "/page/:num/"
excerpt_separator: "<!--more-->"
default_bg: sitelogo.png 
safe: true
timezone:    America/Chicago
future:      false

gems:
  - jekyll-paginate
  - jemoji
  - font-awesome-sass
  - kramdown
  - rouge

include: [".htaccess"]
exclude: ["lib", "config.rb", "Gemfile", "Capfile", "Gemfile.lock", "config", "log", "Rakefile", "Rakefile.rb", "rakefile", "README.md", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "LICENSE", "vendor", "assets", "_plugins", "public/dormant", "CNAME"]

# About/contact
author:
  name: Dan Jones
  url:  http://pile.goodevilgenius.org
  #avatar: 
  #email:           

# Owner/author information
owner:
  name: Dan Jones
  from: Texas, USA
  dribbble:
  avatar:         
  email: 
  facebook: danjones
  flickr: goodevilgenius
  github: goodevilgenius
  instagram: goodevilgenius
  linkedin: danjones000
  pinterest:
  twitter: goodevilgenius
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: +DanJones000 # anything in your profile username that comes after plus.google.com/
  # Use the coder's toolbox at http://coderstoolbox.net/string/#!encoding=xml&action=encode&charset=us_ascii to encode your description into XML string
  description:
  # Social networking links used in footer. Update and remove as you like.
  stackexchange:  users/367461/dan-jones
  tumblr:  
  # orcid and google scholar IDs are different than standard username.
  # orcid: xyz123abc
  # gscholar: xyz123abc

## sidebar links:
# For external links add external: true
links:
  - title: <i class="iconside iconm-home"></i> Home
    url: /
  - title: <i class="iconside iconm-user"></i> About
    url: /about/
  - title: <i class="iconside iconm-quill"></i> Blog
    url: /blog/
  - title: <i class="fa fa-tags"></i> Tags
    url: /tags/
  - title: <i class="fa fa-archive"></i> Archive
    url: /archive/
  - title: <i class="iconside iconm-terminal"></i> Working on &hellip;
    url: https://goodevilgenius.gitbooks.io/batman-last-son-of-krypton/content/v/tween-powers/
    external: true
  - title: <i class="iconside iconm-envelop"></i> Contact
    url: /contact/
  - title: <i class="iconside iconm-twitter"></i> Twitter
    url: https://twitter.com/goodevilgenius
    external: true
  - title: <i class="iconside iconm-feed2"></i> Feed
    url: /feed.xml

# Google Custom Search:
#google_search: xyz123abc

# Twitter stream widget:
# Replace xyz123abc with your twitter widget id from https://twitter.com/settings/widgets
#twitter_widget_id: xyz123abc

# Add disqus username for Disqus comment board:
#disqus_shortname: foo

# Analytics and webmaster tools stuff goes here
#google_analytics:   xyz123abc

## END ##
